name: Deploy Flask to GitHub Pages

on:
  push:
    branches:
      - main  # Run the workflow on changes to the main branch

permissions:
  contents: write  # Allow writing to the repository (used for artifacts)
  pages: write     # Required for GitHub Pages deployments

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages  # Specify the environment here

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up environment
      run: echo "FLASK_ENV=production" >> $GITHUB_ENV

    # Step 4: Run Flask app to generate static files
    - name: Run Flask app to generate static files
      run: |
        mkdir -p build
        python app.py  # Ensure app.py generates static files in the 'build' directory

    # Step 5: Upload artifact for deployment
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: ./build  # Upload the 'build' folder that contains the static files

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages  # Artifact name must match
    permissions:
      id-token: write   # Required for OpenID Connect (OIDC) authentication
      pages: write      # Required for GitHub Pages deployments